---
title: "Marking Rubric: Panel Discussion"
---

Every week we will reserve 20 mins for a panel discussion based on the assigned reading for that day (4-5 papers).
This discussion will include three types of roles: panel members, audience members, and a moderator. Each panel discussion
will include 4 panel members, 1 moderator, and audience members. Panel members are responsible for answering questions,
the audience is responsible for asking questions, and the moderator is responsible for steering the discussion and having
backup questions if the audience is not asking any.

### Panel member evaluation

* Answering questions from the moderator and the audience correctly / well (6 pts)
* Engaging with points of other panelists (1 pts)
* Keeping answers brief / allowing other people time to speak (2 pts)
* Pre-submitting 1-2 questions on Quercus about the assigned papers of the day, the Thursday before lecture (1 pts)

### Audience member evaluation
* Pre-submitting 1-2 questions on Quercus about the assigned papers of the day, the Thursday before lecture (10 pts)

### Moderator (Florian)

* Steering the discussion in terms of groups / themes of questions 
* Ensuring there is time for every panel member to speak
* Engaging the audience / ensuring the audience has enough time to ask questions